<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\YAvuzeli.Infrastructure\YAvuzeli.Infrastructure.csproj" />
    <ProjectReference Include="..\YAvuzeli.Application\YAvuzeli.Application.csproj" />
    <ProjectReference Include="..\YAvuzeli.Shared\YAvuzeli.Shared.csproj" />
  </ItemGroup>
</Project>
